### ISSUE TITLE
Can we use Vagrant for Production Deployments?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-devops#12]
https://www.linode.com/docs/applications/configuration-management/vagrant-linode-environments

**Comment by nelsonic** [comment]
https://www.hashicorp.com/blog/vagrant-push-one-command-to-deploy-any-application/

**Comment by nelsonic** [comment]
while following:
https://www.linode.com/docs/applications/configuration-management/vagrant-linode-environments
attempted to run `vagrant up` ...
I see this error: 
![image](https://user-images.githubusercontent.com/194400/28500942-a06bcad4-6fc9-11e7-9694-d2a7d2ed070e.png)

**Comment by nelsonic** [comment]
Meanwhile the Linode instance _was_ created (_despite the error_):
![image](https://user-images.githubusercontent.com/194400/28501095-72aa7cdc-6fcc-11e7-85cf-e78018426809.png)

**Comment by nelsonic** [comment]
This time it got a bit further:
![image](https://user-images.githubusercontent.com/194400/28501215-2d6b9856-6fcf-11e7-922a-55846dd6478b.png)

It _appears_ to _fail_ but I am able to login to the instance:
![image](https://user-images.githubusercontent.com/194400/28502092-bfdc19be-6fe2-11e7-811d-23c3f9899a96.png)

**Comment by nelsonic** [comment]
Rather than waste time with passwords I've tried using the `root` user:
https://stackoverflow.com/questions/25758737/vagrant-login-as-root-by-default

Still getting a lot of red ... 🤔 
![image](https://user-images.githubusercontent.com/194400/28502237-e7e1e47c-6fe5-11e7-9be5-ea8bb0e1c1b2.png)

**Comment by nelsonic** [comment]
Apache is a fail.
Tried NGiNX following: https://github.com/dwyl/learn-microsoft-azure#12-install--run-nginx-to-test
Totes Works!! 
![image](https://user-images.githubusercontent.com/194400/28502648-95078aa0-6fee-11e7-8c35-8b0604404668.png)

**Comment by MUAFFAK** [comment]
Hi
