### ISSUE TITLE
*single* edeliver command to build and "hot upgrade" a Elixir/Phoenix App?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-devops#19]
picks up from: https://github.com/dwyl/learn-elixir/issues/54
moved here to reduce noise in `learn-elixir` repo which has more watchers...

after updating `distillery` to latest version (`1.4.1`): https://github.com/nelsonic/hello_world_edeliver/commit/3c8f493889b0b660152ae537c890bd3bcc03c5fb
we are _still_ getting an error:
![image](https://user-images.githubusercontent.com/194400/28746224-d35b48c4-747f-11e7-96df-6b9801fe36a5.png)

```
** (EXIT from #PID<0.73.0>) an exception was raised:
    ** (File.Error) could not write to file "/home/ubuntu/hello_world_edeliver/builds/_build/prod/lib/edeliver/ebin/Elixir.Releases.Plugin.LinkConfig.beam": no such file or directory
        (elixir) lib/file.ex:831: File.write!/3
        (mix) lib/mix/compilers/elixir.ex:431: anonymous fn/4 in Mix.Compilers.Elixir.write_manifest/5
        (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
        (mix) lib/mix/compilers/elixir.ex:427: Mix.Compilers.Elixir.write_manifest/5
        (mix) lib/mix/compilers/elixir.ex:166: anonymous fn/4 in Mix.Compilers.Elixir.compile_manifest/8
        (elixir) lib/agent/server.ex:31: Agent.Server.handle_cast/2
        (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:686: :gen_server.handle_msg/6


15:59:25.377 [error] GenServer #PID<0.269.0> terminating
** (File.Error) could not write to file "/home/ubuntu/hello_world_edeliver/builds/_build/prod/lib/edeliver/ebin/Elixir.Releases.Plugin.LinkConfig.beam": no such file or directory
    (elixir) lib/file.ex:831: File.write!/3
    (mix) lib/mix/compilers/elixir.ex:431: anonymous fn/4 in Mix.Compilers.Elixir.write_manifest/5
    (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/compilers/elixir.ex:427: Mix.Compilers.Elixir.write_manifest/5
    (mix) lib/mix/compilers/elixir.ex:166: anonymous fn/4 in Mix.Compilers.Elixir.compile_manifest/8
    (elixir) lib/agent/server.ex:31: Agent.Server.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
Last message: {:"$gen_cast", {:cast, #Function<8.64051268/1 in Mix.Compilers.Elixir.compile_manifest/8>}}

A remote command failed on:

  ubuntu@213.168.248.157

Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:

FAILED with exit status 1:

    [ -f ~/.profile ] && source ~/.profile
    set -e

    cd '/home/ubuntu/hello_world_edeliver/builds'
    APP='hello_world_edeliver' MIX_ENV='prod' mix phoenix.digest

```

**Comment by nelsonic** [comment]
The _build_ is ***working*** on Travis-CI: https://travis-ci.org/nelsonic/hello_world_edeliver/builds/258934703#L1342 
![image](https://user-images.githubusercontent.com/194400/28747695-f1ad39e6-749c-11e7-984d-ef363ecf583e.png)


What if we just _run_: 
```
_build/prod/rel/hello_world_edeliver/bin/hello_world_edeliver start
```
it _works_!
![image](https://user-images.githubusercontent.com/194400/28747712-2c9d38a8-749d-11e7-8636-ea302cbba21c.png)

the only issue is that our `/_version` endpoint no longer works.
so we _could_ just update the handler and we're off to the races!!

**Comment by nelsonic** [comment]
So to re-start the _full_ path would be:
```
/home/ubuntu/hello_world_edeliver/builds/_build/prod/rel/hello_world_edeliver/bin/hello_world_edeliver restart
```

I don't _know_ if this "_gracefully_" restarts the server without dropping connections/WebSockets ...
But equally I don't know it _matters_ yet ...

**Comment by nelsonic** [comment]
_Obviously_, it worked when I did it _manually_ (_see screenshot above_)
But _fails_ when run on Travis-CI:
https://travis-ci.org/nelsonic/hello_world_edeliver/builds/258938636#L747
![image](https://user-images.githubusercontent.com/194400/28747797-9641f706-749f-11e7-8b7e-4f94f9601c7e.png)

This is because Travis (`edeliver`) is trying to over-write the files which are _in use_ by Erlang...
(_i.e. the files are locked!_) 

What's worse, we now have a "Zombie" App:
![image](https://user-images.githubusercontent.com/194400/28747841-56da7150-74a0-11e7-85f4-44d25982816a.png)

The ***Turd*** on the Cake is that the even though the command _clearly **failed**_ on Travis-CI (_see above_), Travis reports that the build ***passed***!!!: 😮 
![image](https://user-images.githubusercontent.com/194400/28747864-f0395212-74a0-11e7-8a3e-31bf23b81583.png)


So we have to run:
```
kill -9 $(lsof -t -i:4000 -sTCP:LISTEN)
```
See: https://stackoverflow.com/questions/11583562/how-to-kill-a-process-running-on-particular-port-in-linux
Which gets us:
![image](https://user-images.githubusercontent.com/194400/28747852-a22705b0-74a0-11e7-9d52-40f5d75bfaa2.png)
With the app "Killed" I can run a `new` Travis Build with `stop` and `start` commands ...

**Comment by nelsonic** [comment]
Build ***Fails***: https://travis-ci.org/nelsonic/hello_world_edeliver/builds/258942560#L832
![image](https://user-images.githubusercontent.com/194400/28747925-83427f9c-74a2-11e7-9db5-ebc377bb2297.png)

Yet Travis-CI Reports "Pass": https://travis-ci.org/nelsonic/hello_world_edeliver/builds/258942560
![image](https://user-images.githubusercontent.com/194400/28747926-914278b8-74a2-11e7-8196-5774d6194e76.png)

This is making me _sad_... 😞

**Comment by nelsonic** [comment]
The "***false positive***" is _really_ disconcerting. 👎 
Let's retry the "build upgrade" command ... 
First run a "basic" (_release_) build (_i.e. non-upgrade_):
```
mix edeliver build release --verbose
```
![image](https://user-images.githubusercontent.com/194400/28748090-32710f8a-74a6-11e7-890b-6e9c299776f3.png)

deploy:
```
mix edeliver deploy release to production
```
![image](https://user-images.githubusercontent.com/194400/28748134-71cf3e3a-74a7-11e7-946f-b5e3be18077a.png)

```
mix edeliver start production
```
![image](https://user-images.githubusercontent.com/194400/28748138-8148dccc-74a7-11e7-935d-a534a21c4482.png)

Location of `.git` file: `/home/ubuntu/hello_world_edeliver/builds`
![image](https://user-images.githubusercontent.com/194400/28748234-5f4b59f8-74aa-11e7-8bd2-f48d50505b09.png)

The App is _working_:
![image](https://user-images.githubusercontent.com/194400/28748269-553af724-74ab-11e7-8abb-41714cefbbdf.png)

But the `/_version`:
![image](https://user-images.githubusercontent.com/194400/28748273-67ebe892-74ab-11e7-8e93-eab8decd2a01.png)

The logs: `cat /home/ubuntu/hello_world_edeliver/var/log/erlang.log.1`
![image](https://user-images.githubusercontent.com/194400/28748266-436588e8-74ab-11e7-872c-c72a0920cdff.png)

**Comment by nelsonic** [comment]
This is what I get for _not_ having a ***test*** for the code ... 😞 
Anyway, I've update the handler so it should work now ...

**Comment by nelsonic** [comment]
Probably should pay attention to the fact that `_build` is being removed during build process:
![image](https://user-images.githubusercontent.com/194400/28748375-251412f8-74ae-11e7-8526-4a956f015b3a.png)

**Comment by nelsonic** [comment]
Works again: http://213.168.248.157/_version
![image](https://user-images.githubusercontent.com/194400/28748394-95a699b4-74ae-11e7-9e50-79f0e9bf4e09.png)

Commit:
![image](https://user-images.githubusercontent.com/194400/28748396-abd8f7d6-74ae-11e7-81f1-026b9f44b278.png)

https://github.com/nelsonic/hello_world_edeliver/commit/7f4a0abcc0c786f6d58fd81f323cf6a6121abc65

**Comment by nelsonic** [comment]
The `build upgrade` command:
```
mix edeliver build upgrade --auto-version=git-revision --from=$(curl http://213.168.248.157/_version) --to=$(git rev-parse HEAD) --verbose
```
![image](https://user-images.githubusercontent.com/194400/28748507-9b893640-74b1-11e7-8c83-21be534fbf9e.png)
Worked!!

but then when I tried:
```
mix edeliver deploy upgrade to production --version=0.0.4+8d62475 --verbose
```
got:
![image](https://user-images.githubusercontent.com/194400/28748517-c300f60e-74b1-11e7-92c3-d92c41d14bff.png)

error message:
```
Unpacked successfully: "0.0.4+8d62475"
Release 0.0.4+8d62475 is already unpacked, now installing.
ERROR: release_handler:check_install_release failed: {enoent,
                                                      "/home/ubuntu/hello_world_edeliver/releases/0.0.4/relup"}
```

investigating the `relup` now ...

**Comment by nelsonic** [comment]
the `build upgrade` command created a `relup` file in the build:
![image](https://user-images.githubusercontent.com/194400/28748617-1d601a74-74b4-11e7-9cbf-90ca26dbb569.png)
`/home/ubuntu/hello_world_edeliver/releases/0.0.4+8d62475/relup` contents:
```
{"0.0.4+8d62475",
 [{"0.0.4+7f4a0ab",[],
   [{load_object_code,
        {hello_world_edeliver,"0.0.4+8d62475",
            ['Elixir.HelloWorldEdeliver.Gettext',
             'Elixir.HelloWorldEdeliver.PageView']}},
    point_of_no_return,
    {load,{'Elixir.HelloWorldEdeliver.Gettext',brutal_purge,brutal_purge}},
    {load,{'Elixir.HelloWorldEdeliver.PageView',brutal_purge,brutal_purge}}]}],
 [{"0.0.4+7f4a0ab",[],
   [{load_object_code,
        {hello_world_edeliver,"0.0.4+7f4a0ab",
            ['Elixir.HelloWorldEdeliver.Gettext',
             'Elixir.HelloWorldEdeliver.PageView']}},
    point_of_no_return,
    {load,{'Elixir.HelloWorldEdeliver.Gettext',brutal_purge,brutal_purge}},
    {load,
        {'Elixir.HelloWorldEdeliver.PageView',brutal_purge,brutal_purge}}]}]}.
```

Attempting to create a `relup` file in: `/home/ubuntu/hello_world_edeliver/releases/0.0.4/relup`

changed `0.0.4+8d62475` to `0.0.4`
and `0.0.4+7f4a0ab` to `0.0.3`

which gives:
```
{"0.0.4",
 [{"0.0.3",[],
   [{load_object_code,
        {hello_world_edeliver,"0.0.4",
            ['Elixir.HelloWorldEdeliver.Gettext',
             'Elixir.HelloWorldEdeliver.PageView']}},
    point_of_no_return,
    {load,{'Elixir.HelloWorldEdeliver.Gettext',brutal_purge,brutal_purge}},
    {load,{'Elixir.HelloWorldEdeliver.PageView',brutal_purge,brutal_purge}}]}],
 [{"0.0.3",[],
   [{load_object_code,
        {hello_world_edeliver,"0.0.3",
            ['Elixir.HelloWorldEdeliver.Gettext',
             'Elixir.HelloWorldEdeliver.PageView']}},
    point_of_no_return,
    {load,{'Elixir.HelloWorldEdeliver.Gettext',brutal_purge,brutal_purge}},
    {load,
        {'Elixir.HelloWorldEdeliver.PageView',brutal_purge,brutal_purge}}]}]}.
```

**Comment by nelsonic** [comment]
Getting closer!! 🔍 

![image](https://user-images.githubusercontent.com/194400/28749151-fdb7f85c-74b5-11e7-9dd2-beeef5742f21.png)
Error:
```
-----> Upgrading release to 0.0.4+8d62475
Release 0.0.4+8d62475 is already unpacked
Release 0.0.4+8d62475 is already unpacked, now installing.
ERROR: release_handler:check_install_release failed: {no_matching_relup,
                                                      "0.0.4+8d62475","0.0.4"}
```
Manually editing: `/home/ubuntu/hello_world_edeliver/releases/0.0.4+8d62475/relup`
changing `0.0.4+7f4a0ab` to `0.0.4` the current release!
```
{"0.0.4+8d62475",
 [{"0.0.4",[],
   [{load_object_code,
        {hello_world_edeliver,"0.0.4+8d62475",
            ['Elixir.HelloWorldEdeliver.Gettext',
             'Elixir.HelloWorldEdeliver.PageView']}},
    point_of_no_return,
    {load,{'Elixir.HelloWorldEdeliver.Gettext',brutal_purge,brutal_purge}},
    {load,{'Elixir.HelloWorldEdeliver.PageView',brutal_purge,brutal_purge}}]}],
 [{"0.0.4",[],
   [{load_object_code,
        {hello_world_edeliver,"0.0.4",
            ['Elixir.HelloWorldEdeliver.Gettext',
             'Elixir.HelloWorldEdeliver.PageView']}},
    point_of_no_return,
    {load,{'Elixir.HelloWorldEdeliver.Gettext',brutal_purge,brutal_purge}},
    {load,
        {'Elixir.HelloWorldEdeliver.PageView',brutal_purge,brutal_purge}}]}]}.
```

**Comment by nelsonic** [comment]
Success!!!  🎉 
![image](https://user-images.githubusercontent.com/194400/28749188-1eea9a24-74b7-11e7-84af-9cae1a017b79.png)

Before:
![image](https://user-images.githubusercontent.com/194400/28749200-5374fdfc-74b7-11e7-8524-58bab9bd9dee.png)

After:
![image](https://user-images.githubusercontent.com/194400/28749204-5b78fdf0-74b7-11e7-8bc4-7fce5bff0082.png)

😢  > 😂

**Comment by nelsonic** [comment]
So the "_only_" thing I need is do is _read_ the latest version from the `.deliver/releases` dir ...
created a file: `.deliver/version.sh`:
```
#!/bin/bash
# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# echo $DIR
FILENAME=$(ls -t "$DIR/releases" | head -n 1)
NO_APP_NAME=$(echo $FILENAME | sed 's/hello_world_edeliver_//g')
VERSION=$(echo $NO_APP_NAME | sed 's/.upgrade.tar.gz//g')
echo $VERSION
```

then I can do: 
```
mix edeliver deploy upgrade to production --version=$(.deliver/version.sh) --verbose
```

**Comment by nelsonic** [comment]
Works _flawlessly_!
![image](https://user-images.githubusercontent.com/194400/28749447-70caca0a-74bf-11e7-9237-d2f419c8bd7e.png)

**Comment by nelsonic** [comment]
On Travis-CI: https://travis-ci.org/nelsonic/hello_world_edeliver/builds/258982249#L1679
![image](https://user-images.githubusercontent.com/194400/28749477-859cd04e-74c0-11e7-941a-bb27d77c0751.png)

![image](https://user-images.githubusercontent.com/194400/28749480-a0718fe0-74c0-11e7-9c09-8e6ebe745fa1.png)

http://213.168.248.157/_version
![image](https://user-images.githubusercontent.com/194400/28749481-acc4b92a-74c0-11e7-919f-bfc58290ddd2.png)

`33e2c56b5f5999cf4815813f11d1f9e977431497` which matches:
https://github.com/nelsonic/hello_world_edeliver/commit/33e2c56b5f5999cf4815813f11d1f9e977431497

I'm a happy bunny again. 🎉

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/28887944-d38c2d10-77b6-11e7-89ea-f9e0fffc1164.png)
```
Release 1.0.3+793b658 is already unpacked
cat: /home/hladmin/healthlocker/releases/1.0.3+793b658/sys.config: No such file or directory
```

**Comment by nelsonic** [comment]
Really sick of having a crappy internet connection and trying to do deployments ... 😞 
![image](https://user-images.githubusercontent.com/194400/28888832-f2c7afd0-77b9-11e7-81ea-39d617d0f92d.png)

**Comment by nelsonic** [comment]
Reading through https://github.com/bitwalker/distillery/blob/master/docs/Runtime%20Configuration.md now...

**Comment by nelsonic** [comment]
Opened:
+ https://github.com/edeliver/edeliver/issues/234
+ https://stackoverflow.com/questions/45478961/how-to-avoid-edeliver-deployment-error-vm-args-no-such-file-or-directory

Sadly, _cannot_ make progress on this until we get some feedback. ⏳

**Comment by daya** [comment]
@nelsonic Thanks for the excellent write ups and sharing. Have you had any success on [edeliver/edeliver#234](https://github.com/edeliver/edeliver/issues/234) ??

**Comment by nelsonic** [comment]
Hi @daya! sadly no "success" _yet_...! 
right now we are doing our Phoenix App deployments _semi-manually_ and it _sucks_! 😞 

However I have been side-tracked working on a "Serverless" (Node.js) project 
for the last couple of months so I haven't _looked_ at this since ... 🙄 
I'm _sure_ it's ***possible*** to _fully automate_ the build process for our Phoenix Apps
and I will be returning to it "_very soon_" (_once my current app ships_).

**Comment by nelsonic** [comment]
Read: https://elixir-lang.org/blog/2019/06/24/elixir-v1-9-0-released/

**Comment by nelsonic** [comment]
No longer using `edeliver`; using `mix release` instead. closing.
