### ISSUE TITLE
Where to save SSH keys for Dokku PaaS

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-devops#47]
In the pre-requisites of the Dokku Paas tutorial, we need to add an SSH key to our droplet" https://github.com/dwyl/learn-devops/blob/bd4489096cf6ed31eb2fb6a8886fb1eae4bfc41f/nodejs-digital-ocean-centos-dokku.md#0-pre-requisites

Part of the process is to [create one](https://www.digitalocean.com/docs/droplets/how-to/add-ssh-keys/create-with-openssh/). 

As someone who is totally new to devops, are there any conventions I should be aware of around where I should save this to? Does scope matter? Can I just make up any name for a file within the project folder where I'm working (without committing it, obviously)?

**Comment by nelsonic** [comment]
@iteles this is just the SSH key on your Mac that you use to push to GitHub.
You need to locate the _public_ key usually `~/.ssh/id_rsa.pub` on your `localhost`
and _copy_ the contents of the file e.g run the following command in your terminal:
```sh
pbcopy < ~/.ssh/id_rsa.pub
```

And then _paste_ that **`public`** key into Digital Ocean UI:

it should look something like this:
```sh
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5lvyvoOry+TRFwDjYWHt4L+6LOlCo9uD47qzQFJVYHNg+TW/QZwbI3eWBElg5i1QlrTfnFGyQD31aj4qukaqsrqx0tsgysUS8nOltrx2IYxSJ1XFqQCETXwNvjns+gasOvg07yoGnczgtsUWWuytQkwu5x8+cGhC08e65AFAYZuam8jHQgsDhOeskN0RzpdyfI7IjNNheTkcHIfgMy+iaZHTDNE95vELdKhu9N8D86B8w==  etc.
```

Let me know if that works for you.

**Comment by iteles** [comment]
It did, thanks!
