### ISSUE TITLE
Three dots (...) as host in phoenix deloyment tutorial

### ISSUE THREAD

**Issue by pizzapim** [dwyl/learn-devops#54]
Hey,

I have been following the Phoenix production deployment guide, and I managed to get it running, so kudos for that!

However, I have a question about the endpoint config that the guide gives. This is the excerpt:
```elixir
config :hello_world_edeliver, HelloWorldEdeliver.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "...", port: {:system, "PORT"}],
```

I'm confused because of the three dots as the host. As far as I know, this has no special meaning as IP address. Does it do anything in particular or is it just ignored?

Thanks in advance!

**Comment by nelsonic** [comment]
Hi @pizzapim thanks for your feedback! We're delighted that the guide was useful to you! 🎉 

The three dots are to allow Phoenix to listen on _any_ IP address, 
this is useful for running your app in a cluster where the IP address could change without warning 
e.g AWS if you spawn nodes dynamically using autoscaling. 

If you know the IP address of your server is not going to change 
you can replace the `...` with the address.

See: https://hexdocs.pm/phoenix/Phoenix.Endpoint.html for more info.

**Comment by pizzapim** [comment]
Thanks @nelsonic ! 

I would've expected they had used ":::" for this purpose, But now I understand.
