### ISSUE TITLE
build tools issue?

### ISSUE THREAD

**Issue by hariharasudhan94** [dwyl/learn-devops#8]
I am trying to deploy to amazon ec2 when i run the  `mix edeliver build release --verbose`, i am getting error like follow 

> -----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
A remote command failed on:
  ec2-user@X.X.X.X
Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:
FAILED with exit status 255:
    set -e
    if [ ! -d /home/ec2-user/xxxx/builds ]
    then
      mkdir -p /home/ec2-user/xxxx/builds
      cd /home/ec2-user/xxxx/builds
      git init 
      git config receive.denyCurrentBranch ignore
    else
      cd /home/ec2-user/xxxx/builds
      git config receive.denyCurrentBranch ignore
    fi

**Comment by nelsonic** [comment]
@hariharasudhan94 this is a question for the Edeliver issue log. (_sorry we are not "experts" **yet**_...)

**Comment by nelsonic** [comment]
@hariharasudhan94 please raise this issue on: https://github.com/edeliver/edeliver/issues
(_there are people with more experience/insight who can help you..._)
